### ISSUE TITLE
Donkey Sim command cannot import the name SteeringServer

### ISSUE THREAD

**Issue by jaskarannagi19** [autorope/donkeycar#339]
Donkey sim

using donkey version: 2.5.7 ...
Traceback (most recent call last):
  File "/home/jaskaran/.conda/envs/DonkeyCar/bin/donkey", line 11, in <module>
    load_entry_point('donkeycar', 'console_scripts', 'donkey')()
  File "/home/jaskaran/donkeycar/donkeycar/management/base.py", line 456, in execute_from_command_line
    c.run(args[2:])
  File "/home/jaskaran/donkeycar/donkeycar/management/base.py", line 258, in run
    from donkeycar.parts.simulation import SteeringServer
ImportError: cannot import name 'SteeringServer'

Any help here

**Comment by scitronboy** [comment]
When did you install donkey? @wroscoe might this be a problem caused by #338 ?

**Comment by jaskarannagi19** [comment]
@scitronboy I installed it 6-7 hours ago

**Comment by jaskarannagi19** [comment]
@scitronboy ok I'll try with older commit than and will let you know in sometime

**Comment by wroscoe** [comment]
Try installing version 2.5.1

**Comment by jaskarannagi19** [comment]
@wroscoe This did help that error is gone

**Comment by macfly1202** [comment]
just install today donkey and see exact same error:
<code>(car) jmp@deep:~/mycar$ donkey sim --model=models/mypilot
using donkey version: 2.5.7 ...
Traceback (most recent call last):
  File "/home/jmp/anaconda3/bin/donkey", line 9, in <module>
    load_entry_point('donkeycar==2.5.7', 'console_scripts', 'donkey')()
  File "/home/jmp/Dropbox/github/donkeycar/car/donkeycar/donkeycar/management/base.py", line 457, in execute_from_command_line
    c.run(args[2:])
  File "/home/jmp/Dropbox/github/donkeycar/car/donkeycar/donkeycar/management/base.py", line 259, in run
    from donkeycar.parts.simulation import SteeringServer
ImportError: cannot import name 'SteeringServer'
</code>

Will try to install previous donkey version...
